package uz.space.coding.quiz

object Constants {
    const val USERNAME: String = "username"
    const val TOTAL_QUESTIONS: String = "total_questions"
    const val CORRECT_ANSWERS: String = "correct_answers"

    fun getCountryNames(): ArrayList<String> {
        return arrayListOf<String>(
            "Afghanistan",
            "Albania",
            "Algeria",
            "Andorra",
            "Angola",
            "Antigua & Barbuda",
            "Argentina",
            "Armenia",
            "Australia",
            "Austria",
            "Azerbaijan",
            "Bahamas",
            "Bahrain",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Belize",
            "Benin",
            "Bhutan",
            "Bolivia",
            "Bosnia and Herzegovina",
            "Botswana",
            "Brazil",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cabo Verde",
            "Cambodia",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chad",
            "Chile",
            "China",
            "Colombia",
            "Comoros",
            "The Democratic Republic of Congo",
            "The Republic of Congo",
            "Costa Rica",
            "Cote d'Ivoire",
            "Croatia",
            "Cuba",
            "Cyprus",
            "Czechia",
            "Denmark",
            "Djibouti",
            "Dominica",
            "Dominican Republic",
            "Ecuador",
            "Egypt",
            "El Salvador",
            "Equatorial Guinea",
            "Eritrea",
            "Estonia",
            "Eswatini",
            "Ethiopia",
            "Fiji",
            "Finland",
            "France",
            "Gabon",
            "Gambia",
            "Georgia",
            "Germany",
            "Ghana",
            "Greece",
            "Grenada",
            "Guatemala",
            "Guinea",
            "Guinea-Bissau",
            "Guyana",
            "Haiti",
            "Honduras",
            "Hungary",
            "Iceland",
            "India",
            "Indonesia",
            "Iran",
            "Iraq",
            "Ireland",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jordan",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kosovo",
            "Kuwait",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Liberia",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Maldives",
            "Mali",
            "Malta",
            "Marshall Islands",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Micronesia",
            "Moldova",
            "Monaco",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Myanmar",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "North Korea",
            "North Macedonia",
            "Norway",
            "Oman",
            "Pakistan",
            "Palau",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Kitts and Nevis",
            "Saint Lucia",
            "Saint Vincent and the Grenadines",
            "Samoa",
            "San Marino",
            "Sao Tome and Principe",
            "Saudi Arabia",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovakia",
            "Slovenia",
            "Solomon Islands",
            "Somalia",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "Sudan",
            "Suriname",
            "Sweden",
            "Switzerland",
            "Syria",
            "Taiwan",
            "Tajikistan",
            "Tanzania",
            "Thailand",
            "Timor-Leste",
            "Togo",
            "Tonga",
            "Trinidad and Tobago",
            "Tunisia",
            "Turkey",
            "Turkmenistan",
            "Tuvalu",
            "Uganda",
            "Ukraine",
            "United Arab Emirates",
            "United Kingdom",
            "United States of America",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Vatican City (Holy See)",
            "Venezuela",
            "Vietnam",
            "Yemen",
            "Zambia",
            "Zimbabwe"
        )
    }

    fun getCountryImages(): ArrayList<Int> {
        return arrayListOf<Int>(
            R.drawable.ic_afghanistan,
            R.drawable.ic_albania,
            R.drawable.ic_algeria,
            R.drawable.ic_andorra,
            R.drawable.ic_angola,
            R.drawable.ic_antigua,
            R.drawable.ic_argentina,
            R.drawable.ic_armenia,
            R.drawable.ic_australia,
            R.drawable.ic_austria,
            R.drawable.ic_azerbaijan,
            R.drawable.ic_bahamas,
            R.drawable.ic_bahrain,
            R.drawable.ic_bangladesh,
            R.drawable.ic_barbados,
            R.drawable.ic_belarus,
            R.drawable.ic_belgium,
            R.drawable.ic_belize,
            R.drawable.ic_benin,
            R.drawable.ic_bhutan,
            R.drawable.ic_bolivia,
            R.drawable.ic_bosnia,
            R.drawable.ic_botswana,
            R.drawable.ic_brazil,
            R.drawable.ic_brunei,
            R.drawable.ic_bulgaria,
            R.drawable.ic_burkina_faso,
            R.drawable.ic_burundi,
            R.drawable.ic_cabo_verde,
            R.drawable.ic_cambodia,
            R.drawable.ic_cameroon,
            R.drawable.ic_canada,
            R.drawable.ic_central_african_republic,
            R.drawable.ic_chad,
            R.drawable.ic_chile,
            R.drawable.ic_china,
            R.drawable.ic_colombia,
            R.drawable.ic_comoros,
            R.drawable.ic_congo_dem,
            R.drawable.ic_congo,
            R.drawable.ic_costa_rica,
            R.drawable.ic_cote,
            R.drawable.ic_croatia,
            R.drawable.ic_cuba,
            R.drawable.ic_cyprus,
            R.drawable.ic_czech,
            R.drawable.ic_denmark,
            R.drawable.ic_djibouti,
            R.drawable.ic_dominica,
            R.drawable.ic_dominican_republic,
            R.drawable.ic_ecuador,
            R.drawable.ic_egypt,
            R.drawable.ic_el_salvador,
            R.drawable.ic_equatorial_guinea,
            R.drawable.ic_eritrea,
            R.drawable.ic_estonia,
            R.drawable.ic_eswatini,
            R.drawable.ic_ethiopia,
            R.drawable.ic_fiji,
            R.drawable.ic_finland,
            R.drawable.ic_france,
            R.drawable.ic_gabon,
            R.drawable.ic_gambia,
            R.drawable.ic_georgia,
            R.drawable.ic_germany,
            R.drawable.ic_ghana,
            R.drawable.ic_greece,
            R.drawable.ic_grenada,
            R.drawable.ic_guatemala,
            R.drawable.ic_guinea,
            R.drawable.ic_guinea_bissau,
            R.drawable.ic_guyana,
            R.drawable.ic_haiti,
            R.drawable.ic_honduras,
            R.drawable.ic_hungary,
            R.drawable.ic_iceland,
            R.drawable.ic_india,
            R.drawable.ic_indonesia,
            R.drawable.ic_iran,
            R.drawable.ic_iraq,
            R.drawable.ic_ireland,
            R.drawable.ic_israel,
            R.drawable.ic_italy,
            R.drawable.ic_jamaica,
            R.drawable.ic_japan,
            R.drawable.ic_jordan,
            R.drawable.ic_kazakhstan,
            R.drawable.ic_kenya,
            R.drawable.ic_kiribati,
            R.drawable.ic_kosovo,
            R.drawable.ic_kuwait,
            R.drawable.ic_kyrgyzstan,
            R.drawable.ic_laos,
            R.drawable.ic_latvia,
            R.drawable.ic_lebanon,
            R.drawable.ic_lesotho,
            R.drawable.ic_liberia,
            R.drawable.ic_libya,
            R.drawable.ic_liechtenstein,
            R.drawable.ic_lithuania,
            R.drawable.ic_luxembourg,
            R.drawable.ic_madagascar,
            R.drawable.ic_malawi,
            R.drawable.ic_malaysia,
            R.drawable.ic_maldives,
            R.drawable.ic_mali,
            R.drawable.ic_malta,
            R.drawable.ic_marshall_islands,
            R.drawable.ic_mauritania,
            R.drawable.ic_mauritius,
            R.drawable.ic_mexico,
            R.drawable.ic_micronesia,
            R.drawable.ic_moldova,
            R.drawable.ic_monaco,
            R.drawable.ic_mongolia,
            R.drawable.ic_montenegro,
            R.drawable.ic_morocco,
            R.drawable.ic_mozambique,
            R.drawable.ic_myanmar,
            R.drawable.ic_namibia,
            R.drawable.ic_nauru,
            R.drawable.ic_nepal,
            R.drawable.ic_netherlands,
            R.drawable.ic_new_zealand,
            R.drawable.ic_nicaragua,
            R.drawable.ic_niger,
            R.drawable.ic_nigeria,
            R.drawable.ic_korea_north,
            R.drawable.ic_north_macedonia,
            R.drawable.ic_norway,
            R.drawable.ic_oman,
            R.drawable.ic_pakistan,
            R.drawable.ic_palau,
            R.drawable.ic_palestine,
            R.drawable.ic_panama,
            R.drawable.ic_papua_new_guinea,
            R.drawable.ic_paraguay,
            R.drawable.ic_peru,
            R.drawable.ic_philippines,
            R.drawable.ic_poland,
            R.drawable.ic_portugal,
            R.drawable.ic_qatar,
            R.drawable.ic_romania,
            R.drawable.ic_russia,
            R.drawable.ic_rwanda,
            R.drawable.ic_st_kitts_nevis,
            R.drawable.ic_st_lucia,
            R.drawable.ic_st_vincent_the_grenadines,
            R.drawable.ic_samoa,
            R.drawable.ic_san_marino,
            R.drawable.ic_sao_tome_and_principe,
            R.drawable.ic_saudi_arabia,
            R.drawable.ic_senegal,
            R.drawable.ic_serbia,
            R.drawable.ic_seychelles,
            R.drawable.ic_sierra_leone,
            R.drawable.ic_singapore,
            R.drawable.ic_slovakia,
            R.drawable.ic_slovenia,
            R.drawable.ic_solomon_islands,
            R.drawable.ic_somalia,
            R.drawable.ic_south_africa,
            R.drawable.ic_korea_south,
            R.drawable.ic_south_sudan,
            R.drawable.ic_spain,
            R.drawable.ic_sri_lanka,
            R.drawable.ic_sudan,
            R.drawable.ic_suriname,
            R.drawable.ic_sweden,
            R.drawable.ic_switzerland,
            R.drawable.ic_syria,
            R.drawable.ic_taiwan,
            R.drawable.ic_tajikistan,
            R.drawable.ic_tanzania,
            R.drawable.ic_thailand,
            R.drawable.ic_timor_leste,
            R.drawable.ic_togo,
            R.drawable.ic_tonga,
            R.drawable.ic_trinidad_and_tobago,
            R.drawable.ic_tunisia,
            R.drawable.ic_turkey,
            R.drawable.ic_turkmenistan,
            R.drawable.ic_tuvalu,
            R.drawable.ic_uganda,
            R.drawable.ic_ukraine,
            R.drawable.ic_united_arab_emirates,
            R.drawable.ic_united_kingdom,
            R.drawable.ic_united_states_of_america,
            R.drawable.ic_uruguay,
            R.drawable.ic_uzbekistan,
            R.drawable.ic_vanuatu,
            R.drawable.ic_vatican_city,
            R.drawable.ic_venezuela,
            R.drawable.ic_vietnam,
            R.drawable.ic_yemen,
            R.drawable.ic_zambia,
            R.drawable.ic_zimbabwe
        )
    }

    fun getQuestions(numberOfQuestions: Int): ArrayList<Question> {
        val questions = ArrayList<Question>()

        for (i in 1..numberOfQuestions) {
            questions.add(generateQuestion(i)!!)
        }

        return questions
    }

    private fun generateQuestion(id: Int): Question? {
        val correctOption = (1..4).random()

        val countryNames = getCountryNames()
        val countryImages = getCountryImages()
        val countrySize = countryNames.size
        val questionIndex = (0 until countrySize).random()
        val questionString = "What country does this flag belong to?"

        var result: Question? = null

        when (correctOption) {
            1 -> {
                result = Question(
                    id,
                    questionString,
                    countryImages!![questionIndex],
                    countryNames!![questionIndex],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    correctOption
                )
            }
            2 -> {
                result = Question(
                    id,
                    questionString,
                    countryImages!![questionIndex],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    countryNames!![questionIndex],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    correctOption
                )
            }
            3 -> {
                result = Question(
                    id,
                    questionString,
                    countryImages!![questionIndex],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    countryNames!![questionIndex],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    correctOption
                )
            }
            4 -> {
                result = Question(
                    id,
                    questionString,
                    countryImages!![questionIndex],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    countryNames!![getRandomNumberExceptN(0, countrySize, questionIndex)],
                    countryNames!![questionIndex],
                    correctOption
                )
            }
        }

        return result
    }

    private fun getRandomNumberExceptN(from: Int, to: Int, n: Int): Int {
        val res = (from until to).random()

        if (res == n) {
            return getRandomNumberExceptN(from, to, n)
        }

        return res
    }
}